<?php

namespace Murky\BiblioBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BiblioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BiblioRepository extends EntityRepository
{
}
